name: 'setup-minikube'
description: 'test your app against real Kubernetes.'
author: 'Medya Gh'
branding:
  icon: 'box'  
  color: 'blue'
inputs:
  minikube-version:
    description: 'Choose a specific version of minikube, "latest" for the latest stable build, or "HEAD" for the latest development build'
    required: false
    default: 'latest'
  driver:
    description: 'Choose a specific driver, one of: docker, none, podman, virtualbox, parallels, vmwarefusion, hyperkit, vmware, ssh'
    required: false
    default: ''
  container-runtime:
    description: 'Choose a specific container-runtime, one of: docker, containerd, cri-o'
    required: false
    default: ''
  kubernetes-version:
    description: 'Choose a specific version of Kubernetes, "stable" for the latest stable build, or "latest" for the latest development build'
    required: false
    default: ''
  cpus:
    description: 'Number of CPUs allocated to Kubernetes. Use "max" to use the maximum number of CPUs.'
    required: false
    default: ''
  memory:
    description: 'Amount of RAM to allocate to Kubernetes (format: <number>[<unit>], where unit = b, k, m or g). Use "max" to use the maximum amount of memory.'
    required: false
    default: ''
  cni:
    description: 'CNI plug-in to use. Valid options: auto, bridge, calico, cilium, flannel, kindnet, or path to a CNI manifest'
    required: false
    default: 'auto'
  extra-config:
    description: 'Extra configuration (--extra-config) to pass into "minikube start".'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
